table dim_date
	lineageTag: 7f242509-4f03-4818-bb05-8463d1257d8f

	column date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 1cb4ab0e-b09b-4d43-8802-791a80eb6532
		summarizeBy: none
		sourceColumn: date

		variation Variation
			isDefault
			relationship: 4283c497-2174-4894-bd1b-f04dde4407e4
			defaultHierarchy: LocalDateTable_925f1578-cfa3-414d-b3d3-b80a3564e49f.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'mmm yy'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 302db26b-bc72-46b9-906e-70e917e54da4
		summarizeBy: none
		sourceColumn: mmm yy

		variation Variation
			isDefault
			relationship: 9651b3fc-51bc-4a89-88cc-28c73c04590b
			defaultHierarchy: LocalDateTable_26642032-4721-4ba9-a2d9-796766e5c221.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'week no'
		dataType: string
		lineageTag: 4b3f2c2a-6e10-4a29-bfec-d56f27a6363c
		summarizeBy: none
		sourceColumn: week no

		annotation SummarizationSetBy = Automatic

	column wn = WEEKNUM(dim_date[date])
		formatString: 0
		lineageTag: 3a75135f-1773-47a6-8ed6-5ea58e2958b3
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column day_type = ```
			
			 var war=WEEKDAY(dim_date[date])
			 RETURN if(war>5,"Weekend","Weekday")
			```
		lineageTag: c752cc9e-10ec-470c-97aa-e48afd1515e3
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition dim_date = m
		mode: import
		source =
				let
				    Source = Folder.Files("C:\path\to\hotel-booking-analytics\data"),
				    #"C:\path\to\hotel-booking-analytics\data\_dim_date csv" = Source{[#"Folder Path"="C:\path\to\hotel-booking-analytics\data\",Name="dim_date.csv"]}[Content],
				    #"Imported CSV" = Csv.Document(#"C:\path\to\hotel-booking-analytics\data\_dim_date csv",[Delimiter=",", Columns=4, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(#"Imported CSV", [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"date", type date}, {"mmm yy", type date}, {"week no", type text}, {"day_type", type text}}),
				    #"Removed Columns:day_type" = Table.RemoveColumns(#"Changed Type",{"day_type"})
				in
				    #"Removed Columns:day_type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

