table dim_rooms
	lineageTag: 4642a577-72df-43bc-b4a5-0f61c52088de

	column room_id
		dataType: string
		lineageTag: f07fd3d5-baae-4248-a218-dfaa49da6b46
		summarizeBy: none
		sourceColumn: room_id

		annotation SummarizationSetBy = Automatic

	column room_class
		dataType: string
		lineageTag: 5a27c696-cbb7-44ca-ab79-ba43dabad554
		summarizeBy: none
		sourceColumn: room_class

		annotation SummarizationSetBy = Automatic

	partition dim_rooms = m
		mode: import
		source =
				let
				    Source = Folder.Files("C:\path\to\hotel-booking-analytics\data"),
				    #"C:\path\to\hotel-booking-analytics\data\_dim_rooms csv" = Source{[#"Folder Path"="C:\path\to\hotel-booking-analytics\data\",Name="dim_rooms.csv"]}[Content],
				    #"Imported CSV" = Csv.Document(#"C:\path\to\hotel-booking-analytics\data\_dim_rooms csv",[Delimiter=",", Columns=2, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Imported CSV",{{"Column1", type text}, {"Column2", type text}}),
				    #"Promoted Headers" = Table.PromoteHeaders(#"Changed Type", [PromoteAllScalars=true]),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Promoted Headers",{{"room_id", type text}, {"room_class", type text}})
				in
				    #"Changed Type1"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

