table fact_bookings
	lineageTag: 171a8542-9f99-44fb-ae9c-a9e2433cf6fe

	column booking_id
		dataType: string
		lineageTag: f545321f-5120-4e16-a63d-e8e5fe764146
		summarizeBy: none
		sourceColumn: booking_id

		annotation SummarizationSetBy = Automatic

	column property_id
		dataType: int64
		formatString: 0
		lineageTag: cbf1f46a-046f-4d28-b3c5-b66e90fea74d
		summarizeBy: none
		sourceColumn: property_id

		annotation SummarizationSetBy = Automatic

	column booking_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 0ebd65b6-d3a3-4bd6-978f-a61bb6c23615
		summarizeBy: none
		sourceColumn: booking_date

		variation Variation
			isDefault
			relationship: 1c3d445c-4620-45fe-b767-d30dc1367923
			defaultHierarchy: LocalDateTable_ebc7932d-dcda-4004-b95f-6a1a3a696d9c.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column check_in_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: ff147c8e-51ae-4f0e-90b9-66f95f0656b1
		summarizeBy: none
		sourceColumn: check_in_date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column checkout_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: c0ea32ce-3c7a-473f-ba97-2718ac3f5948
		summarizeBy: none
		sourceColumn: checkout_date

		variation Variation
			isDefault
			relationship: 3c41a3b7-2962-465f-ade4-d7bfcbb64542
			defaultHierarchy: LocalDateTable_ba171211-01a0-47dd-9f7a-5fb1e7123e66.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column no_guests
		dataType: int64
		formatString: 0
		lineageTag: 50dc3c06-6760-4553-bb0f-aaed93fe86c8
		summarizeBy: sum
		sourceColumn: no_guests

		annotation SummarizationSetBy = Automatic

	column room_category
		dataType: string
		lineageTag: 99a0bec6-66e4-4f88-9933-ec68714879ef
		summarizeBy: none
		sourceColumn: room_category

		annotation SummarizationSetBy = Automatic

	column booking_platform
		dataType: string
		lineageTag: e975fcb2-82ca-404e-9aac-aca88f600271
		summarizeBy: none
		sourceColumn: booking_platform

		annotation SummarizationSetBy = Automatic

	column ratings_given
		dataType: int64
		formatString: 0
		lineageTag: 03ae790f-7d8d-45ed-9df1-a93b4d990a2a
		summarizeBy: sum
		sourceColumn: ratings_given

		annotation SummarizationSetBy = Automatic

	column booking_status
		dataType: string
		lineageTag: 21131732-11d8-43fe-8ec9-c90207f5ce9c
		summarizeBy: none
		sourceColumn: booking_status

		annotation SummarizationSetBy = Automatic

	column revenue_generated
		dataType: int64
		formatString: 0
		lineageTag: bca9f01b-ffde-4546-b8e0-19dff0180b05
		summarizeBy: sum
		sourceColumn: revenue_generated

		annotation SummarizationSetBy = Automatic

	column revenue_realized
		dataType: int64
		formatString: 0
		lineageTag: 4f972870-26f8-4db2-943d-6d65d39358cd
		summarizeBy: sum
		sourceColumn: revenue_realized

		annotation SummarizationSetBy = Automatic

	partition fact_bookings = m
		mode: import
		source =
				let
				    Source = Folder.Files("C:\path\to\hotel-booking-analytics\data"),
				    #"C:\path\to\hotel-booking-analytics\data\_fact_bookings csv" = Source{[#"Folder Path"="C:\path\to\hotel-booking-analytics\data\",Name="fact_bookings.csv"]}[Content],
				    #"Imported CSV" = Csv.Document(#"C:\path\to\hotel-booking-analytics\data\_fact_bookings csv",[Delimiter=",", Columns=12, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(#"Imported CSV", [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"booking_id", type text}, {"property_id", Int64.Type}, {"booking_date", type date}, {"check_in_date", type date}, {"checkout_date", type date}, {"no_guests", Int64.Type}, {"room_category", type text}, {"booking_platform", type text}, {"ratings_given", Int64.Type}, {"booking_status", type text}, {"revenue_generated", Int64.Type}, {"revenue_realized", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

